CREATE TYPE "UserRole" AS ENUM (
  'PLAYER',
  'ADMIN'
);

CREATE TYPE "Element" AS ENUM (
  'FIRE',
  'ICE',
  'EARTH',
  'WIND',
  'LIGHT',
  'DARK',
  'LIGHTNING'
);

CREATE TYPE "Rarity" AS ENUM (
  'COMMON',
  'UNCOMMON',
  'RARE',
  'EPIC',
  'LEGENDARY'
);

CREATE TYPE "EnemyType" AS ENUM (
  'GOBLIN',
  'SKELETON',
  'ORC',
  'TROLL',
  'SLIME'
);

CREATE TYPE "PotionType" AS ENUM (
  'HEALTH',
  'MANA'
);

CREATE TYPE "BuffType" AS ENUM (
  'ATTACK',
  'DEFENSE',
  'HEALTH',
  'MANA'
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(20) UNIQUE NOT NULL,
  "password" varchar(50) NOT NULL,
  "role" "UserRole" NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE "Weapon" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "attack" int NOT NULL,
  "mana" int NOT NULL,
  "element" "Element" NOT NULL,
  "rarity" "Rarity" NOT NULL
);

CREATE TABLE "Skill" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "attack" int NOT NULL,
  "mana" int NOT NULL,
  "cooldown" int NOT NULL,
  "element" "Element" NOT NULL,
  "rarity" "Rarity" NOT NULL
);

CREATE TABLE "Enemy" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "hp" int NOT NULL,
  "defense" int NOT NULL,
  "attack" int NOT NULL,
  "element" "Element" NOT NULL,
  "enemyType" "EnemyType" NOT NULL
);

CREATE TABLE "Boss" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "hp" int NOT NULL,
  "defense" int NOT NULL,
  "attack" int NOT NULL,
  "element" "Element" NOT NULL,
  "skillId" int NOT NULL,
  "enemyType" "EnemyType" NOT NULL
);

CREATE TABLE "Buff" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "buffType" "BuffType" NOT NULL,
  "buffMultiplier" int NOT NULL,
  "rarity" "Rarity" NOT NULL
);

CREATE TABLE "Difficulty" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "baseHp" int NOT NULL,
  "baseMana" int NOT NULL,
  "baseAttack" int NOT NULL,
  "baseDefense" int NOT NULL
);

CREATE TABLE "PlayerState" (
  "username" varchar(20) PRIMARY KEY,
  "hp" int NOT NULL,
  "currentHp" int NOT NULL,
  "mana" int NOT NULL,
  "currentMana" int NOT NULL,
  "defense" int NOT NULL,
  "attack" int NOT NULL,
  "element" "Element" NOT NULL,
  "weaponId" int,
  "skillId" int NOT NULL,
  "currentStage" int NOT NULL DEFAULT 1
);

CREATE TABLE "Potion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "potionType" "PotionType" NOT NULL,
  "potionEffect" int NOT NULL,
  "rarity" "Rarity" NOT NULL
);

ALTER TABLE "Boss" ADD FOREIGN KEY ("skillId") REFERENCES "Skill" ("id");

ALTER TABLE "PlayerState" ADD FOREIGN KEY ("username") REFERENCES "User" ("username");

ALTER TABLE "PlayerState" ADD FOREIGN KEY ("weaponId") REFERENCES "Weapon" ("id");

ALTER TABLE "PlayerState" ADD FOREIGN KEY ("skillId") REFERENCES "Skill" ("id");

INSERT INTO "User" ("username", "password", "role", "created_at") VALUES
('admin', 'admin', 'ADMIN', NOW()),
('b', 'b', 'PLAYER', NOW()),
('c', 'c', 'PLAYER', NOW());

-- Difficulty
INSERT INTO "Difficulty" ("name", "baseHp", "baseMana", "baseAttack", "baseDefense") VALUES
('Easy', 150, 70, 15, 10),
('Medium', 100, 50, 10, 5),
('Hard', 80, 30, 8, 3);

-- Skill (Termasuk skill default)
-- ID 1-7 adalah skill default
INSERT INTO "Skill" ("name", "attack", "mana", "cooldown", "element", "rarity") VALUES
('Ember', 10, 10, 3, 'FIRE', 'COMMON'),
('Ice Shard', 10, 10, 3, 'ICE', 'COMMON'),
('Rock Throw', 10, 10, 3, 'EARTH', 'COMMON'),
('Gust', 10, 10, 3, 'WIND', 'COMMON'),
('Light Beam', 10, 10, 3, 'LIGHT', 'COMMON'),
('Shadow Ball', 10, 10, 3, 'DARK', 'COMMON'),
('Spark', 10, 10, 3, 'LIGHTNING', 'COMMON'),
-- Skill Gacha
('Fireball', 25, 20, 4, 'FIRE', 'UNCOMMON'),
('Blizzard', 50, 40, 6, 'ICE', 'RARE'),
('Earthquake', 60, 50, 7, 'EARTH', 'EPIC'),
('Holy Smite', 100, 80, 10, 'LIGHT', 'LEGENDARY');

-- Weapon
INSERT INTO "Weapon" ("name", "attack", "mana", "element", "rarity") VALUES
('Fire Staff', 10, 5, 'FIRE', 'RARE'),
('Thunder Hammer', 30, 15, 'LIGHTNING', 'EPIC'),
('Excalibur', 70, 30, 'LIGHT', 'LEGENDARY');

INSERT INTO "Weapon" ("id","name", "attack", "mana", "element", "rarity") VALUES
(0, 'none', 0, 0, 'LIGHT', 'LEGENDARY');

-- Potion
INSERT INTO "Potion" ("name", "potionType", "potionEffect", "rarity") VALUES
('Small Health Potion', 'HEALTH', 25, 'COMMON'),
('Small Mana Potion', 'MANA', 25, 'COMMON'),
('Medium Health Potion', 'HEALTH', 50, 'UNCOMMON'),
('Medium Mana Potion', 'MANA', 50, 'UNCOMMON'),
('Large Health Potion', 'HEALTH', 100, 'RARE');

-- Buff
INSERT INTO "Buff" ("name", "buffType", "buffMultiplier", "rarity") VALUES
('Small Attack Boost', 'ATTACK', 10, 'COMMON'),  -- +10%
('Small Defense Boost', 'DEFENSE', 10, 'COMMON'),
('Attack Boost', 'ATTACK', 25, 'UNCOMMON'),
('Defense Boost', 'DEFENSE', 25, 'UNCOMMON'),
('Max HP Boost', 'HEALTH', 20, 'RARE'),
('Major Attack Boost', 'ATTACK', 50, 'EPIC');

-- Enemy
INSERT INTO "Enemy" ("name", "hp", "defense", "attack", "element", "enemyType") VALUES
('Goblin Scout', 30, 3, 5, 'EARTH', 'GOBLIN'),
('Goblin Warrior', 50, 5, 8, 'EARTH', 'GOBLIN'),
('Skeleton Archer', 25, 2, 7, 'DARK', 'SKELETON'),
('Armored Skeleton', 60, 10, 6, 'DARK', 'SKELETON'),
('Slime', 20, 8, 4, 'WIND', 'SLIME'),
('Orc Grunt', 80, 8, 12, 'EARTH', 'ORC');

-- Boss (Gunakan ID 9 = Blizzard dari tabel Skill)
INSERT INTO "Boss" ("name", "hp", "defense", "attack", "element", "skillId", "enemyType") VALUES
('Grom the Orc Chief', 200, 15, 20, 'EARTH', 9, 'ORC'),
('Ice Golem', 300, 20, 15, 'ICE', 9, 'TROLL');